all:
  children:
    nginx:
      hosts:
        nginx01:
          ansible_host: 52.195.245.5
    webapp:
      hosts:
        webapp01:
          ansible_host: 52.195.245.5
    db:
      hosts:
        db01:
          ansible_host: 192.168.0.12
